# 🌻비동기 자바스크립트
javascript의 꽃

### 콜백(callback)이란?
어떤 함수의 아규먼트로 전달되는 함수를 **콜백** 또는 **콜백 함수**라고 부릅니다.

```js
// function 키워드로 선언한 함수를 콜백으로 사용(콜백 파라미터 없음)
function printMessage(func) {
  console.log('Printing message...');
  func();
}

function sayHello() {
  console.log('Hello World!');
}

printMessage(sayHello);
```
```
Printing message...
Hello World!
```
```js
// Arrow Function을 콜백으로 사용(콜백 파라미터 없음)
function printMessage(func) {
  console.log('Printing message...');
  func();
}

printMessage(() => console.log('Hello World!'));
```
```
Printing message...
Hello World!
```
```js
// function 키워드로 선언한 함수를 콜백으로 사용(콜백 파라미터 있음)
function printMessageWithParams(func, name) {
  console.log('Printing message...');
  func(name);
}

function sayHello(name) {
  console.log(`Hello ${name}!`);
}

printMessageWithParams(sayHello, 'Bob');
```
```
Printing message...
Hello Bob!
```
```js
// Arrow Function을 콜백으로 사용(콜백 파라미터 있음)
function printMessageWithParams(func, name) {
  console.log('Printing message...');
  func(name);
}

printMessageWithParams((name) => console.log(`Hello ${name}!`), 'Bob');
```
```
Printing message...
Hello Bob!
```

### 콜백과 비동기 함수
`setTimeout()` 함수는 특정 시간이 지난 후에 콜백을 실행하는 함수입니다. 기다리는 동안에는 함수 아래에 있는 코드를 실행합니다.

```js
console.log('1');

setTimeout(() => console.log('2'), 3000);

console.log('3');
```
```
1
3
2
```
![alt text](/images/비동기.png)
`setTimeout()` 함수는 내용을 끝까지 다 실행하지 않고 중간에 다른 코드를 실행하다가 다시 함수 안으로 돌아오는데요. 이런 함수를 **비동기 함수**라고 부릅니다. 콜백을 이용하면 나중에 할 작업을 함수 형태로 전달해 줄 수 있기 때문에 비동기 함수에 많이 쓰입니다.

[다른 비동기 함수들](https://www.codeit.kr/topics/asynchronous-javascript/lessons/6183)(`setInterval()`, DOM의 `addEventListener()` 등)을  자세히 알 수 있습니다.

### 콜백의 한계(callback Hell)
콜백을 이용해서 비동기 프로그램을 짤 수 있다는 것은 좋지만 한계점이 있습니다. 여러 비동기 작업을 연속적으로 처리하는 것입니다.
```js
// 직원 데이터를 가져온 후 리스폰스를 파싱하고 데이터를 프로세싱 하는 예시
getEmployees((response) => {
  json(response, (data) => {
    groupEmployees(data, (result) => {
      console.log(result);
    });
  });
});
```
콜백 기반 코드는 모든 작업을 함수 안에서 처리하기 때문에 작업을 이어서 하려면 콜백 안에 콜백을 등록해야 합니다. 그렇기 때문에 콜백을 중첩해서 사용해야 하는 이런 현상을 **콜백 헬(callback Hell)**이라고 부릅니다. 

콜백 헬(callback Hell)로 인해 코드를 이해하기도 힘들고, 디버깅이나 테스팅 같은 걸 하기도 어렵기 때문에 이러한 불편함을 해소하기 위해 **Promise**가 등장했습니다.

### Promise
> **Promise**는 비동기 작업이 완료되면 값을 알려주는 객체입니다.

- Pending: 비동기 작업이 끝나기를 기다릴 때
- Fulfilled: 비동기 작업이 성공적으로 끝났을 때, 비동기 작업의 성공 결과를 결괏값으로 갖게 됨.
- Rejected: 비동기 작업이 실패했을 때, 비동기 작업에서 발생한 오류를 결괏값으로 갖게 됨.

Promise는 이렇게 세 가지 상태를 갖고있습니다.

### `async`, `await` 문법
> `async` / `await`문법은 Promise 객체를 다루는 방법 중 하나입니다.

```js
const result = await Promise;

// 예시
const response = await fetch('https://learn.codeit.kr/api/employees');
```
Promise 객체 앞에 `awiat` 키워드를 쓰면 Promise의 상태가 fulfilled 또는 rejected가 될 때까지 기다립니다.
- Fulfilled 상태가 되면 Promise 객체의 결괏값을 리턴
- Rejected 상태가 되면 Promise 객체의 결괏값(error)을 throw합니다.

> Promise 객체의 값을 가져오려면 항상 앞에 `await`을 꼭 붙여야 합니다.

`await`은 보통 `async` 함수 안에서 사용합니다. ES 모듈의 경우, 함수 바깥에서도 사용할 수 있습니다.

```js
// 일반 function
async function printEmployees() {
  const response = await fetch('https://learn.codeit.kr/api/employees');
  const data = await response.json();
  console.log(data);
}

// Arrow function
const printEmployees = async () => {
  const response = await fetch('https://learn.codeit.kr/api/employees');
  const data = await response.json();
  console.log(data);
}
```
`async` 함수는 안에서 `awiat`을 마주치면, 함수 바깥으로 나가서 나머지 코드를 실행하다가 Promise 객체가 fulfilled 또는 rejected 상태가 되면 다시 함수 안으로 돌아와서 코드를 실행합니다.

```js
async function printEmployees() {
  const response = await fetch('https://learn.codeit.kr/api/employees');
  const data = await response.json();
  console.log(data);
}

printEmployees();

console.log('Task 2');
console.log('Task 3');
```
```
Task 2
Task 3
[
  {
    id: 1,
    name: 'Jason',
    email: 'jason@codeitmall.kr',
    department: 'engineering'
  },
  ...
]
```
`async` 함수는 항상 Promise를 리턴합니다.
- 함수 안에서 Promise를 리턴하면 그 Promise를 그대로 리턴합니다.
- 함수 안에서 평범한 값을 리턴하면 그 값을 결괏값으로 갖는 Promise를 리턴합니다.

따라서 `async` 함수에서 리턴하는 값을 가져오려면 `await`을 활용해야 합니다.
```js
async function getEmployees() {
  const response = await fetch('https://learn.codeit.kr/api/employees');
  const data = await response.json();
  return data;
}

const employees = await getEmployees(); // await을 생략하면 employees에 Promise 객체가 할당됩니다.
```

### 오류 처리
try, catch를 이용해서 오류를 처리할 수 있습니다.
```js
async function printEmployees() {
  try {
    const response = await fetch('https://learn.codeit.krrrrr/api/employees');
    const data = await response.json();
    console.log(data);
  } catch (error) {
    console.log('error!');
  }
}
```
오류가 발생할 만한 코드를 `try`로 감싸 주고, `catch` 안에서 오류를 처리하면 됩니다. 발생한 오류는 `catch`문의 error 변수에 전달되기 때문에 이걸 활용할 수도 있습니다.

만약 `try`, `catch`문의 결과와 상관없이 끝에 항상 실행해야 하는 코드가 있다면 `finally`문을 사용하면 됩니다.

```js
async function printEmployees() {
  try {
    const response = await fetch('https://learn.codeit.krrrrr/api/employees');
    const data = await response.json();
    console.log(data);
  } catch (error) {
    console.log('error!');
    return;
  } finally {
    console.log('finished');
  }
}
```
위 코드에서, 오류가 발생해서 `catch` 문에서 `return`을 해도 `console.log('finished')`는 실행됩니다.

### `.then()` 메소드
`.then()`은 Promise 객체의 메소드입니다.
```js
fetch('https://learn.codeit.kr/api/employees')
  .then((response) => response.json())
  .then((data) => console.log(data));

console.log('Task 2');
console.log('Task 3');
```
```
Task 2
Task 3
[
  {
    id: 1,
    name: 'Jason',
    email: 'jason@codeitmall.kr',
    department: 'engineering'
  },
  ...
]
```
`.then()`은 앞선 Promise 객체가 fulfilled 상태가 될 때까지 기다렸다가 fulfilled 상태가 되면 안에 있는 콜백을 실행합니다. 이때 앞선 Promise의 결괏값을 콜백의 아규먼트로 전달합니다. 앞선 Promise를 기다리는 동안에는 이후에 있는 코드를 실행합니다.

그리고 `.then()`도 항상 Promise를 리턴합니다.
- `.then()`안의 콜백이 Promise를 리턴할 경우 Promise를 그대로 리턴합니다.
- `.then()`안의 콜백이 평범한 값을 리턴할 경우 이 값을 결괏값으로 가지는 Promise를 리턴합니다.

따라서 `.then()`을 연결해서 쓸 수 있고, 이걸 Promise 체인이라고 부릅니다.

### `.then()` 오류 처리
Promise 체인에서는 `.catch()`, `.finally()` 메소드를 이용해서 오류 처리를 할 수 있습니다.

```js
fetch('https://learn.codeit.krrrr/api/employees')
  .then((response) => response.json())
  .then((data) => console.log(data))
  .catch((error) => console.log('error!'))
  .finally(() => console.log('finished'));
```
- `.then()`은 앞선 Promise가 fulfilled 상태가 되면 안에 있는 콜백을 실행합니다. 이때 앞선 Promise의 결괏값을 콜백의 아규먼트로 전달합니다.
- `.catch()`는 앞선 Promise가 rejected 상태가 되면 안에 있는 콜백을 실행합니다. 이때 앞선 Promise의 결괏값(오류)을 콜백의 아규먼트로 전달합니다.
- `.finally()`는 앞선 Promise가 fulfilled 또는 rejected 상태가 되면 안에 있는 콜백을 실행합니다.

`.then()`의 경우 앞선 Promise가 rejected 상태가 되면 콜백을 실행하지 않고, 앞선 Promise를 그대로 리턴합니다. 따라서 rejected된 Promise는 `.catch()` 전까지 전파됩니다. 대부분의 경우 `.catch()`와 `.finally()`를 Promise 체인 마지막 부분에 씁니다.


### `Promise.all()`
`Promise.all([p1, p2, p3, ...])`은 여러 Promise를 동시에 기다릴 때 사용합니다. `Promise.all()` 자체도 Promise를 리턴하는데요. 아래와 같이 상태가 바뀝니다.
- 아규먼트로 전달된 Promise들이 모두 fulfilled 상태가 되면 `Promise.all()`이 리턴하는 Promise도 fulfilled 상태가 됩니다. 그리고 아규먼트로 전달되는 Promise의 성공 결괏값들로 이루어진 배열을 결괏값으로 갖게 됩니다.
- 아규먼트로 전달된 Promise 중 하나라도 rejected 상태가 되면 `Promise.all()`이 리턴하는 Promise는 rejected 상태가 됩니다. 그리고 rejected된 Promise의 결괏값(오류)을 결괏값으로 갖게 됩니다.

> `Promise.all()`은 여러 비동기 작업을 한꺼번에 처리할 때 유용하게 쓰입니다.
```js
async function getEmployee(id) {
  const response = await fetch(`https://learn.codeit.kr/api/employees/${id}`);
  const data = await response.json();
  return data;
}

const promises = [];

for (let i = 1; i < 11; i++) {
  promises.push(getEmployee(i));
}

let employees;

try {
  employees = await Promise.all(promises);
} catch (error) {
  console.log(error);
}

console.log(employees);
```
```
[
  {
    id: 1,
    name: 'Jason',
    email: 'jason@codeitmall.kr',
    department: 'engineering'
  },
  {
    id: 2,
    name: 'Alice',
    email: 'alice@codeitmall.kr',
    department: 'engineering'
  },
  ...
]
```